#include "elit21/wallet.hpp"

#include <functional>
#include <stdexcept>

namespace elit21 {

Wallet::Wallet(std::string address, std::string secret, std::uint64_t initial_balance)
    : address_(std::move(address)),
      secret_(std::move(secret)),
      balance_(initial_balance),
      nonce_(0) {
    if (address_.empty() || secret_.empty()) {
        throw std::runtime_error("wallet address/secret cannot be empty");
    }
}

const std::string& Wallet::address() const { return address_; }
std::uint64_t Wallet::balance() const { return balance_; }
std::uint64_t Wallet::nonce() const { return nonce_; }

SignedTransaction Wallet::create_signed_payment(const std::string& to,
                                                std::uint64_t amount,
                                                std::uint64_t fee,
                                                const std::string& memo) {
    if (!can_afford(amount, fee)) {
        throw std::runtime_error("insufficient funds");
    }

    Transaction tx;
    tx.from = address_;
    tx.to = to;
    tx.amount = amount;
    tx.fee = fee;
    tx.nonce = nonce_;
    tx.memo = memo;

    if (!is_valid_transaction(tx)) {
        throw std::runtime_error("invalid transaction generated by wallet");
    }

    SignedTransaction signed_tx;
    signed_tx.tx = tx;
    signed_tx.signature = sign(tx);

    ++nonce_;
    return signed_tx;
}

bool Wallet::can_afford(std::uint64_t amount, std::uint64_t fee) const {
    return balance_ >= (amount + fee);
}

void Wallet::apply_debit(std::uint64_t amount, std::uint64_t fee) {
    if (!can_afford(amount, fee)) {
        throw std::runtime_error("insufficient funds");
    }
    balance_ -= amount + fee;
}

void Wallet::apply_credit(std::uint64_t amount) {
    balance_ += amount;
}

bool Wallet::verify_signature(const SignedTransaction& signed_tx) const {
    return sign(signed_tx.tx) == signed_tx.signature;
}

std::string Wallet::sign(const Transaction& tx) const {
    const auto seed = tx.id() + "|" + address_ + "|" + secret_;
    return std::to_string(std::hash<std::string>{}(seed));
}

}  // namespace elit21
